services:
  service-name:
    build:
      context: ./${FLOWCHART_EXECUTOR}/.build
      dockerfile: Dockerfile
    image: ${FLOWCHART_EXECUTOR}_image
    volumes:
      - ./${FLOWCHART_EXECUTOR}:${CONTAINER_VOLUME}
    working_dir: ${CONTAINER_VOLUME}
    # command: ["bash", "run.sh"]
    stdin_open: true
    tty: true